# -*- coding: utf-8 -*-
"""Audited company destinations, matched by normalized whole name tokens."""
from __future__ import annotations

import re
import json
import unicodedata
from pathlib import Path
from urllib.parse import quote_plus

BRANDS = [
    ("arrow generiques", "https://www.arrowgeneriques.com"),
    ("arrow génériques", "https://www.arrowgeneriques.com"),
    ("jamp pharma", "https://www.jamppharma.com"),
    ("eg sa-nv", "https://www.eurogenerics.com"),
    ("eg s.p.a", "https://egstada.it/azienda"),
    ("eg spa", "https://egstada.it/azienda"),
    ("eg sa", "https://www.eurogenerics.com"),
    ("alembic pharmaceuticals", "https://alembicpharmaceuticals.com"),
    ("alembic", "https://alembicpharmaceuticals.com"),
    ("pharmascience inc", "https://www.pharmascience.com"),
    ("pharmascience", "https://www.pharmascience.com"),
    ("g.l. pharma", "https://www.gl-pharma.at"),
    ("gl pharma", "https://www.gl-pharma.at"),
    ("boiron sociedad iberica", "https://www.boiron.es"),
    ("boiron, messimy", "https://www.boiron.fr"),
    ("boiron", "https://www.boiron.com"),
    ("lehning", "https://www.lehning.com"),
    ("weleda", "https://www.weleda.com"),
    ("chartwell rx", "https://www.chartwellpharma.com"),
    ("chartwell", "https://www.chartwellpharma.com"),
    ("doc generici", "https://www.docgenerici.it"),
    ("swisse wellness", "https://swisse.com"),
    ("swisse", "https://swisse.com"),
    ("abacus medicine", "https://www.abacusmedicine.com"),
    ("ce.m.o.n", "https://www.cemon.it"),
    ("cemon", "https://www.cemon.it"),
    ("iberica de homeopatia", "https://www.boiron.es"),
    ("parlogis", "https://www.parlogis.is"),
    ("sanis health", "https://www.sanis.com"),
    ("rising pharma", "https://www.risingpharma.com"),
    ("rising", "https://www.risingpharma.com"),
    ("auro pharma", "https://www.aurobindo.com"),
    ("mepha pharma", "https://www.mepha.ch"),
    ("mepha", "https://www.mepha.ch"),
    ("spirig healthcare", "https://www.spirig.ch"),
    ("spirig", "https://www.spirig.ch"),
    ("pro doc limitee", "https://www.prodoc.qc.ca"),
    ("pro doc", "https://www.prodoc.qc.ca"),
    ("laboratorios normon", "https://www.normon.es"),
    ("normon", "https://www.normon.es"),
    ("msn laboratories", "https://www.msnlabs.com"),
    ("gm pharma international", "https://www.gmpharma.com.au"),
    ("hering s.r.l", "https://www.labhering.com.br"),
    ("haleon australia", "https://www.haleon.com"),
    ("haleon", "https://www.haleon.com"),
    ("b braun australia", "https://www.bbraun.com.au"),
    ("b braun", "https://www.bbraun.com"),
    ("reckitt benckiser", "https://www.reckitt.com"),
    ("reckitt", "https://www.reckitt.com"),
    ("sigma company", "https://www.sigmahealthcare.com.au"),
    ("sigma healthcare", "https://www.sigmahealthcare.com.au"),
    ("jntl consumer health", "https://www.kenvue.com"),
    ("jntl", "https://www.kenvue.com"),
    ("boucher & muir", "https://www.bml.com.au"),
    ("novartis europharm", "https://www.novartis.com"),
    ("novartis pharmaceuticals australia", "https://www.novartis.com/au-en"),
    ("novartis pharma", "https://www.novartis.com"),
    ("astrazeneca pty", "https://www.astrazeneca.com.au"),
    ("astrazeneca uk", "https://www.astrazeneca.com"),
    ("astrazeneca ab", "https://www.astrazeneca.com"),
    ("astrazeneca", "https://www.astrazeneca.com"),
    ("sanofi-aventis australia", "https://www.sanofi.com.au"),
    ("sanofi-aventis", "https://www.sanofi.com"),
    ("sanofi aventis", "https://www.sanofi.com"),
    ("sanofi winthrop", "https://www.sanofi.com"),
    ("sanofi", "https://www.sanofi.com"),
    ("glaxosmithkline", "https://www.gsk.com"),
    ("gsk australia", "https://au.gsk.com"),
    ("pfizer australia", "https://www.pfizer.com.au"),
    ("pfizer europe", "https://www.pfizer.com"),
    ("pfizer limited", "https://www.pfizer.com"),
    ("pfizer pfe", "https://www.pfizer.com"),
    ("pfizer", "https://www.pfizer.com"),
    ("roche registration", "https://www.roche.com"),
    ("roche products", "https://www.roche.com.au"),
    ("roche", "https://www.roche.com"),
    ("genentech", "https://www.gene.com"),
    ("johnson & johnson", "https://www.jnj.com"),
    ("janssen", "https://www.janssen.com"),
    ("bristol-myers squibb", "https://www.bms.com"),
    ("bristol-myers", "https://www.bms.com"),
    ("bristol myers", "https://www.bms.com"),
    ("boehringer ingelheim pty", "https://www.boehringer-ingelheim.com.au"),
    ("boehringer", "https://www.boehringer-ingelheim.com"),
    ("merck sharp", "https://www.msd.com"),
    ("msd australia", "https://www.msd-australia.com.au"),
    ("abbvie pty", "https://www.abbvie.com.au"),
    ("abbvie", "https://www.abbvie.com"),
    ("amgen australia", "https://www.amgen.com.au"),
    ("amgen europe", "https://www.amgen.com"),
    ("amgen", "https://www.amgen.com"),
    ("eli lilly", "https://www.lilly.com"),
    ("lilly australia", "https://www.lilly.com.au"),
    ("lilly", "https://www.lilly.com"),
    ("gilead sciences pty", "https://www.gilead.com"),
    ("gilead sciences ireland", "https://www.gilead.com"),
    ("gilead sciences", "https://www.gilead.com"),
    ("gilead", "https://www.gilead.com"),
    ("takeda pharmaceuticals australia", "https://www.takeda.com"),
    ("takeda pharma", "https://www.takeda.com"),
    ("takeda gmbh", "https://www.takeda.com"),
    ("takeda", "https://www.takeda.com"),
    ("astellas pty", "https://www.astellas.com/au"),
    ("astellas pharma", "https://www.astellas.com"),
    ("astellas", "https://www.astellas.com"),
    ("daiichi sankyo", "https://www.daiichisankyo.com"),
    ("daiichi", "https://www.daiichisankyo.com"),
    ("novo nordisk", "https://www.novonordisk.com"),
    ("novonordisk", "https://www.novonordisk.com"),
    ("accord healthcare ireland", "https://www.accord-healthcare.com"),
    ("accord healthcare france", "https://www.accord-healthcare.com"),
    ("accord healthcare s.l", "https://www.accord-healthcare.com"),
    ("accord healthcare ltd", "https://www.accord-healthcare.com"),
    ("accord healthcare", "https://www.accord-healthcare.com"),
    ("teva pharma australia", "https://www.tevapharm.com"),
    ("teva czech industries", "https://www.tevapharm.com"),
    ("teva italia", "https://www.tevapharm.com"),
    ("teva sante", "https://www.tevapharm.com"),
    ("teva pharma", "https://www.tevapharm.com"),
    ("teva b.v", "https://www.tevapharm.com"),
    ("teva czech", "https://www.tevapharm.com"),
    ("teva", "https://www.tevapharm.com"),
    ("sandoz pharmaceuticals", "https://www.sandoz.com"),
    ("sandoz pty", "https://www.sandoz.com"),
    ("sandoz gmbh", "https://www.sandoz.com"),
    ("sandoz s.r.l", "https://www.sandoz.com"),
    ("sandoz a/s", "https://www.sandoz.com"),
    ("sandoz as", "https://www.sandoz.com"),
    ("novartis sandoz", "https://www.sandoz.com"),
    ("sandoz", "https://www.sandoz.com"),
    ("viatris healthcare", "https://www.viatris.com"),
    ("viatris pharma", "https://www.viatris.com"),
    ("viatris pty", "https://www.viatris.com"),
    ("viatris up", "https://www.viatris.com"),
    ("viatris", "https://www.viatris.com"),
    ("bgp pharma ulc", "https://www.viatris.com"),
    ("bgp pharma", "https://www.viatris.com"),
    ("mylan s.a.s", "https://www.viatris.com"),
    ("mylan eod", "https://www.viatris.com"),
    ("mylan", "https://www.viatris.com"),
    ("meda pharma", "https://www.viatris.com"),
    ("alphapharm", "https://www.viatris.com"),
    ("upjohn", "https://www.viatris.com"),
    ("aspen pharmacare", "https://www.aspenpharma.com"),
    ("aspen australia", "https://www.aspenpharma.com.au"),
    ("aspen", "https://www.aspenpharma.com"),
    ("sun pharmaceutical industries", "https://sunpharma.com"),
    ("sun pharma anz", "https://sunpharma.com"),
    ("sun pharmaceutical", "https://sunpharma.com"),
    ("sun pharma", "https://sunpharma.com"),
    ("ranbaxy", "https://sunpharma.com"),
    ("dr. reddy's", "https://www.drreddys.com"),
    ("dr reddy's", "https://www.drreddys.com"),
    ("dr. reddy", "https://www.drreddys.com"),
    ("dr reddy", "https://www.drreddys.com"),
    ("cipla australia", "https://www.cipla.com"),
    ("cipla eu", "https://www.cipla.com"),
    ("cipla", "https://www.cipla.com"),
    ("krka, d.d", "https://www.krka.biz"),
    ("krka d.d", "https://www.krka.biz"),
    ("krka polska", "https://www.krka.biz"),
    ("krka", "https://www.krka.biz"),
    ("zentiva, k.s", "https://www.zentiva.com"),
    ("zentiva k.s", "https://www.zentiva.com"),
    ("zentiva", "https://www.zentiva.com"),
    ("eg (eurogenerics)", "https://www.eurogenerics.com"),
    ("eurogenerics nv", "https://www.eurogenerics.com"),
    ("eurogenerics", "https://www.eurogenerics.com"),
    ("eg labo", "https://www.eurogenerics.com"),
    ("rowex limited", "https://www.rowex.ie"),
    ("rowex", "https://www.rowex.ie"),
    ("hexal ag", "https://www.hexal.de"),
    ("hexal", "https://www.hexal.de"),
    ("ratiopharm gmbh", "https://www.ratiopharm.de"),
    ("ratiopharm", "https://www.ratiopharm.de"),
    ("stada arz", "https://www.stada.com"),
    ("stada gmbh", "https://www.stada.com"),
    ("stada medicinali", "https://www.stada.com"),
    ("stada nordic", "https://www.stada.com"),
    ("stada", "https://www.stada.com"),
    ("actavis group", "https://www.tevapharm.com"),
    ("actavis italy", "https://www.tevapharm.com"),
    ("actavis", "https://www.tevapharm.com"),
    ("pliva hrvatska", "https://www.tevapharm.com"),
    ("pliva", "https://www.tevapharm.com"),
    ("organon", "https://www.organon.com"),
    ("servier laboratories", "https://servier.com"),
    ("les laboratoires servier", "https://servier.com"),
    ("laboratoires servier", "https://servier.com"),
    ("servier", "https://servier.com"),
    ("lundbeck", "https://www.lundbeck.com"),
    ("ferring pharmaceuticals", "https://www.ferring.com"),
    ("ferring gmbh", "https://www.ferring.com"),
    ("ferring a/s", "https://www.ferring.com"),
    ("ferring", "https://www.ferring.com"),
    ("chiesi farmaceutici", "https://www.chiesi.com"),
    ("chiesi australia", "https://www.chiesi.com.au"),
    ("chiesi limited", "https://www.chiesi.com"),
    ("chiesi", "https://www.chiesi.com"),
    ("recordati rare", "https://www.recordati.com"),
    ("recordati s.p.a", "https://www.recordati.com"),
    ("recordati", "https://www.recordati.com"),
    ("a. menarini", "https://www.menarini.com"),
    ("menarini international", "https://www.menarini.com"),
    ("menarini australia", "https://www.menarini.com.au"),
    ("menarini", "https://www.menarini.com"),
    ("grunenthal gmbh", "https://www.grunenthal.com"),
    ("grunenthal italia", "https://www.grunenthal.com"),
    ("grünenthal", "https://www.grunenthal.com"),
    ("grunenthal", "https://www.grunenthal.com"),
    ("almirall hermal", "https://www.almirall.com"),
    ("almirall s.a", "https://www.almirall.com"),
    ("almirall", "https://www.almirall.com"),
    ("ucb pharma sa", "https://www.ucb.com"),
    ("ucb pharma", "https://www.ucb.com"),
    ("ipsen pharma", "https://www.ipsen.com"),
    ("ipsen pty", "https://www.ipsen.com"),
    ("ipsen", "https://www.ipsen.com"),
    ("pierre fabre medicament", "https://www.pierre-fabre.com"),
    ("pierre fabre", "https://www.pierre-fabre.com"),
    ("laboratoire biogaran", "https://www.biogaran.com"),
    ("biogaran", "https://www.biogaran.com"),
    ("leo pharma pty", "https://www.leo-pharma.com.au"),
    ("leo pharma a/s", "https://www.leo-pharma.com"),
    ("leo pharma", "https://www.leo-pharma.com"),
    ("orion pharma a/s", "https://www.orionpharma.com"),
    ("orion corporation", "https://www.orionpharma.com"),
    ("orion pharma", "https://www.orionpharma.com"),
    ("orion", "https://www.orionpharma.com"),
    ("otsuka pharmaceutical", "https://www.otsuka.com"),
    ("otsuka europe", "https://www.otsuka.com"),
    ("otsuka", "https://www.otsuka.com"),
    ("eisai europe", "https://www.eisai.com"),
    ("eisai gmbh", "https://www.eisai.com"),
    ("eisai", "https://www.eisai.com"),
    ("shionogi b.v", "https://www.shionogi.com"),
    ("shionogi", "https://www.shionogi.com"),
    ("csl behring gmbh", "https://www.cslbehring.com"),
    ("csl behring", "https://www.cslbehring.com"),
    ("csl seqirus", "https://www.seqirus.com"),
    ("seqirus pty", "https://www.seqirus.com"),
    ("seqirus uk", "https://www.seqirus.com"),
    ("seqirus", "https://www.seqirus.com"),
    ("csl limited", "https://www.csl.com"),
    ("csl", "https://www.csl.com"),
    ("moderna biotech", "https://www.modernatx.com"),
    ("moderna", "https://www.modernatx.com"),
    ("biontech manufacturing", "https://www.biontech.com"),
    ("biontech", "https://www.biontech.com"),
    ("b. braun", "https://www.bbraun.com"),
    ("braun melsungen", "https://www.bbraun.com"),
    ("bbraun", "https://www.bbraun.com"),
    ("b.braun", "https://www.bbraun.com"),
    ("orifarm healthcare", "https://www.orifarm.com"),
    ("orifarm a/s", "https://www.orifarm.com"),
    ("orifarm", "https://www.orifarm.com"),
    ("grindeks as", "https://grindeks.com"),
    ("grindeks", "https://grindeks.com"),
    ("kyowa kirin holdings", "https://www.kyowakirin.com"),
    ("kyowa kirin", "https://www.kyowakirin.com"),
    ("medac gesellschaft", "https://www.medac.de"),
    ("medac gmbh", "https://www.medac.de"),
    ("medac", "https://www.medac.de"),
    ("desitin arzneimittel", "https://www.desitin.de"),
    ("desitin", "https://www.desitin.de"),
    ("terapia s.a", "https://www.terapia.ro"),
    ("terapia", "https://www.terapia.ro"),
    ("olpha as", "https://olpha.eu"),
    ("olpha", "https://olpha.eu"),
    ("medical valley invest", "https://www.medicalvalley.se"),
    ("medical valley", "https://www.medicalvalley.se"),
    ("xiromed", "https://www.xiromed.com"),
    ("ge healthcare as", "https://www.gehealthcare.com"),
    ("ge healthcare", "https://www.gehealthcare.com"),
    ("landauer radiopharmaceuticals", "https://www.landauer.com"),
    ("landauer", "https://www.landauer.com"),
    ("techdow pharma netherlands", "https://www.techdow.com"),
    ("techdow pharma", "https://www.techdow.com"),
    ("2care4 generics aps", "https://www.2care4.dk"),
    ("2care4 generics", "https://www.2care4.dk"),
    ("2care4", "https://www.2care4.dk"),
    ("bayer australia", "https://www.bayer.com.au"),
    ("bayer pharma", "https://www.bayer.com"),
    ("bayer ag", "https://www.bayer.com"),
    ("bayer", "https://www.bayer.com"),
    ("gsk", "https://www.gsk.com"),
    ("msd", "https://www.msd.com"),
    ("merck kgaa", "https://www.merck.com"),
    ("merck serono", "https://www.merck.com"),
    ("merck sante", "https://www.merck.com"),
    ("novartis", "https://www.novartis.com"),
    ("hikma farmaceutica", "https://www.hikma.com"),
    ("hikma", "https://www.hikma.com"),
    ("apotex europe", "https://www.apotex.com"),
    ("apotex pty", "https://www.apotex.com"),
    ("apotex", "https://www.apotex.com"),
    ("aurobindo pharma b.v", "https://www.aurobindo.com"),
    ("aurobindo pharma", "https://www.aurobindo.com"),
    ("aurobindo", "https://www.aurobindo.com"),
    ("milpharm limited", "https://www.aurobindo.com"),
    ("milpharm", "https://www.aurobindo.com"),
    ("glenmark pharmaceuticals", "https://glenmarkpharma.com"),
    ("glenmark", "https://glenmarkpharma.com"),
    ("alkem", "https://www.alkemlabs.com"),
    ("biocon", "https://www.biocon.com"),
    ("hetero", "https://www.heteroworld.com"),
    ("wockhardt uk", "https://www.wockhardt.com"),
    ("wockhardt", "https://www.wockhardt.com"),
    ("lupin europe", "https://www.lupin.com"),
    ("lupin", "https://www.lupin.com"),
    ("torrent pharma", "https://www.torrentpharma.com"),
    ("torrent", "https://www.torrentpharma.com"),
    ("zydus france", "https://zyduslife.com"),
    ("zydus worldwide", "https://zyduslife.com"),
    ("zydus", "https://zyduslife.com"),
    ("cadila healthcare", "https://zyduslife.com"),
    ("cadila", "https://zyduslife.com"),
    ("intas pharmaceuticals", "https://www.intaspharma.com"),
    ("intas", "https://www.intaspharma.com"),
    ("alvogen ipco", "https://www.alvogen.com"),
    ("alvogen", "https://www.alvogen.com"),
    ("adamed pharma", "https://adamed.com"),
    ("adamed", "https://adamed.com"),
    ("polpharma s.a", "https://www.polpharma.com"),
    ("polpharma", "https://www.polpharma.com"),
    ("gedeon richter australia", "https://www.gedeonrichter.com"),
    ("gedeon richter plc", "https://www.gedeonrichter.com"),
    ("gedeon richter", "https://www.gedeonrichter.com"),
    ("egis gyogyszergyar", "https://www.egis.hu"),
    ("egis pharmaceuticals", "https://www.egis.hu"),
    ("egis", "https://www.egis.hu"),
    ("berlin-chemie ag", "https://www.berlin-chemie.com"),
    ("berlin-chemie", "https://www.berlin-chemie.com"),
    ("berlin chemie", "https://www.berlin-chemie.com"),
    ("angelini pharma", "https://www.angelinipharma.com"),
    ("angelini spa", "https://www.angelinipharma.com"),
    ("angelini", "https://www.angelinipharma.com"),
    ("alfasigma s.p.a", "https://www.alfasigma.com"),
    ("alfasigma spa", "https://www.alfasigma.com"),
    ("alfasigma", "https://www.alfasigma.com"),
    ("ibsa institut", "https://www.ibsa.com"),
    ("ibsa pharma", "https://www.ibsa.com"),
    ("ibsa", "https://www.ibsa.com"),
    ("pharmaco australia", "https://www.pharmaco.co.nz"),
    ("pharmaco", "https://www.pharmaco.co.nz"),
    ("fresenius kabi australia", "https://www.fresenius-kabi.com/au"),
    ("fresenius kabi", "https://www.fresenius-kabi.com"),
    ("fresenius", "https://www.fresenius.com"),
    ("baxter healthcare pty", "https://www.baxter.com.au"),
    ("baxter healthcare", "https://www.baxter.com"),
    ("baxter", "https://www.baxter.com"),
    ("abbott australasia", "https://www.abbott.com.au"),
    ("abbott laboratories", "https://www.abbott.com"),
    ("abbott healthcare", "https://www.abbott.com"),
    ("abbott", "https://www.abbott.com"),
    ("alcon laboratories australia", "https://www.alcon.com"),
    ("alcon nederland", "https://www.alcon.com"),
    ("alcon laboratories", "https://www.alcon.com"),
    ("alcon", "https://www.alcon.com"),
    ("biogen netherlands", "https://www.biogen.com"),
    ("biogen", "https://www.biogen.com"),
    ("regeneron ireland", "https://www.regeneron.com"),
    ("regeneron", "https://www.regeneron.com"),
    ("vertex pharmaceuticals", "https://www.vrtx.com"),
    ("vertex", "https://www.vrtx.com"),
    ("alexion europe", "https://www.alexion.com"),
    ("alexion", "https://www.alexion.com"),
    ("celgene", "https://www.bms.com"),
    ("mundipharma pharmaceuticals", "https://www.mundipharma.com"),
    ("mundipharma pty", "https://www.mundipharma.com.au"),
    ("mundipharma gmbh", "https://www.mundipharma.com"),
    ("mundipharma", "https://www.mundipharma.com"),
    ("norgine limited", "https://www.norgine.com"),
    ("norgine b.v", "https://www.norgine.com"),
    ("norgine", "https://www.norgine.com"),
    ("santen australia", "https://www.santen.com"),
    ("santen oy", "https://www.santen.com"),
    ("santen", "https://www.santen.com"),
    ("laboratoires thea", "https://www.laboratoires-thea.com"),
    ("thea", "https://www.laboratoires-thea.com"),
    ("bausch + lomb", "https://www.bausch.com"),
    ("bausch & lomb", "https://www.bausch.com.au"),
    ("bausch lomb", "https://www.bausch.com"),
    ("bausch health", "https://www.bauschhealth.com"),
    ("bausch", "https://www.bausch.com"),
    ("galderma australia", "https://www.galderma.com/au"),
    ("galderma international", "https://www.galderma.com"),
    ("galderma sa", "https://www.galderma.com"),
    ("galderma", "https://www.galderma.com"),
    ("stiefel", "https://www.gsk.com"),
    ("aristo pharma", "https://www.aristo-pharma.de"),
    ("aristo", "https://www.aristo-pharma.de"),
    ("betapharm", "https://www.betapharm.de"),
    ("1 a pharma", "https://www.1apharma.com"),
    ("1a pharma", "https://www.1apharma.com"),
    ("bluefish pharmaceuticals", "https://www.bluefishpharma.com"),
    ("bluefish", "https://www.bluefishpharma.com"),
    ("besins healthcare ireland", "https://www.besins-healthcare.com"),
    ("besins healthcare", "https://www.besins-healthcare.com"),
    ("besins", "https://www.besins-healthcare.com"),
    ("exeltis australia", "https://www.exeltis.com"),
    ("exeltis germany", "https://www.exeltis.com"),
    ("exeltis", "https://www.exeltis.com"),
    ("olainfarm", "https://olainfarm.com"),
    ("arrow pharmaceuticals", "https://www.arrowpharma.com.au"),
    ("generic health", "https://www.generichealth.com.au"),
    ("trb chemedica", "https://www.trbchemedica.com"),
    ("macleods", "https://www.macleodspharma.com"),
    ("strides", "https://www.strides.com"),
    ("micro labs gmbh", "https://www.microlabsgmbh.de/"),
    ("micro labs", "https://www.microlabs.com"),
    ("arrotex pharmaceuticals", "https://arrotex.com.au"),
    ("arrotex", "https://arrotex.com.au"),
    ("juno pharmaceuticals", "https://junopharm.com.au"),
    ("juno", "https://junopharm.com.au"),
    ("pharmacor pty", "https://www.pharmacor.com.au"),
    ("pharmacor", "https://www.pharmacor.com.au"),
    ("medsurge healthcare", "https://www.medsurge.com.au"),
    ("medsurge", "https://www.medsurge.com.au"),
    ("link medical products", "https://www.linkmedical.com.au"),
    ("noumed pharmaceuticals", "https://noumed.com.au"),
    ("noumed", "https://noumed.com.au"),
    ("aft pharmaceuticals", "https://www.aftpharm.com"),
    ("mayne pharma", "https://www.maynepharma.com"),
    ("inova pharmaceuticals", "https://inovapharma.com"),
    ("inova", "https://inovapharma.com"),
    ("ego pharmaceuticals", "https://www.egopharm.com"),
    ("southern cross pharma", "https://www.southernxpharma.com.au"),
    ("orion laboratories", "https://www.orionpharma.com"),
    ("aspen pharmacare australia", "https://www.aspenpharma.com.au"),
    ("generic health pty", "https://www.generichealth.com.au"),
    ("arrow pharmaceuticals pty", "https://www.arrowpharma.com.au"),
    ("apotex pty", "https://www.apotex.com"),
    ("accord", "https://www.accord-healthcare.com"),
    ("bms", "https://www.bms.com"),
    ("chugai pharmaceutical", "https://www.chugai-pharm.co.jp"),
    ("chugai", "https://www.chugai-pharm.co.jp"),
    ("shionogi", "https://www.shionogi.com"),
    ("santen pharmaceutical", "https://www.santen.com"),
    ("santen", "https://www.santen.com"),
    ("aska pharmaceutical", "https://www.aska-pharma.co.jp"),
    ("moderna japan", "https://www.modernatx.com"),
    ("moderna", "https://www.modernatx.com"),
    ("eisai", "https://www.eisai.com"),
    ("otsuka pharmaceutical", "https://www.otsuka.com"),
    ("otsuka", "https://www.otsuka.com"),
    ("kyowa kirin", "https://www.kyowakirin.com"),
    ("ono pharmaceutical", "https://www.ono-pharma.com"),
    ("mitsubishi tanabe", "https://www.mt-pharma.co.jp"),
    ("sumitomo pharma", "https://www.sumitomo-pharma.com"),
    ("taisho pharmaceutical", "https://www.taisho.co.jp"),
    ("hisamitsu", "https://global.hisamitsu.com"),
    ("kyorin", "https://www.kyorin-pharm.co.jp"),
    ("meiji seika", "https://www.meiji.com"),
    ("fujifilm", "https://www.fujifilm.com"),
    ("terumo", "https://www.terumo.com"),
    ("nippon kayaku", "https://www.nipponkayaku.com"),
    ("ptc therapeutics", "https://www.ptcbio.com"),
    ("krka", "https://www.krka.biz"),
    ("polpharma", "https://www.polpharma.com"),
    ("alkaloid", "https://alkaloid.com.mk"),
    ("bial - portela", "https://www.bial.com"),
    ("bial", "https://www.bial.com"),
    ("cheplapharm", "https://www.cheplapharm.com"),
    ("fresenius kabi", "https://www.fresenius-kabi.com"),
    ("orion corporation", "https://www.orionpharma.com"),
    ("medcor pharmaceuticals", "https://www.medcor.nl"),
    ("eureco-pharma", "https://www.eureco-pharma.nl"),
    ("pharmadia", "https://www.pharmadia.lt"),
    ("ardeypharm", "https://www.ardeypharm.de"),
    ("alliance healthcare", "https://www.alliance-healthcare.com"),
    ("a a h pharmaceuticals", "https://www.aah.co.uk"),
    ("aah pharmaceuticals", "https://www.aah.co.uk"),
    ("sigma pharmaceuticals", "https://www.sigmapharmaceuticals.co.uk"),
    ("deutsche homöopathie-union", "https://www.dhu.com"),
    ("deutsche homoopathie-union", "https://www.dhu.com"),
    ("inpharm", "https://inpharm.com.pl"),
    ("delfarma", "https://www.delfarma.pl"),
    ("generis farmaceutica", "https://www.generis.pt"),
    ("generis farmace", "https://www.generis.pt"),
    ("laboratorios cinfa", "https://www.cinfa.com"),
    ("cinfa", "https://www.cinfa.com"),
    ("stallergenes", "https://www.stallergenesgreer.com"),
    ("phoenix healthcare", "https://www.phoenixmedical.co.uk"),
    ("kern pharma", "https://www.kernpharma.com"),
    ("aliud pharma", "https://www.aliud.de"),
    ("medochemie", "https://www.medochemie.com"),
    ("wala heilmittel", "https://www.wala.ch"),
    ("aurovitas", "https://www.aurobindo.com"),
]


def fallback_company_url(name: str) -> str:
    """Never guess jurisdiction or invent a company profile URL."""
    return "https://www.google.com/search?q=" + quote_plus(name)


def normalize_name(name):
    return " ".join(re.sub(r"[^\w]+", " ", "".join(c for c in unicodedata.normalize("NFKD", name.casefold()) if not unicodedata.combining(c))).split())


def company_sites(rows) -> dict:
    path = Path(__file__).parent / "data/company-link-resolutions.json"
    verified = json.loads(path.read_text(encoding="utf-8"))["links"] if path.exists() else {}
    brands = sorted([(normalize_name(n), u) for n, u in BRANDS], key=lambda x: len(x[0]), reverse=True)
    out = {}
    for r in rows:
        name = r.get("company") or ""
        if not name or name in out:
            continue
        key = " " + normalize_name(name) + " "
        match = next((site for needle, site in brands if " " + needle + " " in key), None)
        link = verified.get(match)
        out[name] = dict(link) if link else {"url": fallback_company_url(name), "kind": "search"}
    return out
