const assert = require('node:assert/strict');
const {mergeRows, strengthMatches, queryMatches} = require('./_data_logic');
const row = (cc, overrides = {}) => Object.assign([cc,'substance','Product','tablet','10 mg','Company',cc === 'EMA' ? 'e' : 'd'], overrides);
let result = mergeRows([row('EMA'),row('FR')]);
assert.equal(result.length, 1);
assert.equal(result[0][0], 'FR', 'Equal completeness prefers national dump');
assert.deepEqual(new Set(result[0]._sources), new Set(['d','e']));
result = mergeRows([row('FR',{3:'',4:''}), row('EMA')]);
assert.equal(result.length,1);
assert.equal(result[0][0],'EMA','More complete EMA must win');
result = mergeRows([row('EMA',{3:'',4:''}),row('FR')]);
assert.equal(result[0][0],'FR','More complete dump must win');
assert.equal(mergeRows([row('EMA'),row('FR',{2:'Another brand'})]).length,2,'Preserve different brands');
assert.equal(mergeRows([row('EMA'),row('FR',{4:'20 mg'})]).length,2,'Preserve different strengths');
assert.equal(mergeRows([row('EMA'),row('FR',{3:'capsule'})]).length,2,'Preserve different forms');
assert.equal(mergeRows([row('EMA'),row('FR',{5:'Another MAH'})]).length,2,'Preserve conflicting holders');
assert.equal(mergeRows([row('EMA'),row('FR',{4:'0.01 g'})]).length,1,'Equivalent units');
result = mergeRows([row('EMA',{3:'',4:''}),row('EMA'),row('EMA',{4:'20 mg'}),row('FR',{2:'Local only'})]);
assert.equal(result.length,3,'Keep all presentations and local-only products');
assert.ok(strengthMatches('0.5 mg','500 mcg'));
assert.ok(strengthMatches('10 MG','10'));
assert.ok(strengthMatches('0,5 mg','0.5 mg'));
assert.ok(!strengthMatches('10 mg/ml','10 mg'),'Never confuse concentration and mass');
assert.ok(!strengthMatches('10 mg / 20 mg','10 mg'),'Never treat a combination as a single dose');
const baoAn = 'cong ty co phan duoc my pham bao an';
const vipharco = 'paracetamol cong ty co phan duoc pham vipharco';
const tenamyd = 'vitamin cong ty co phan duoc pham tenamyd';
assert.ok(queryMatches(baoAn, baoAn.split(' ')), 'exact company phrase');
assert.ok(!queryMatches(vipharco, baoAn.split(' ')), 'an must not match inside phan');
assert.ok(!queryMatches(tenamyd, baoAn.split(' ')), 'company tokens must not leak across fields');
assert.ok(queryMatches('atorvastatin calcium 20mg company', ['atorvastatin','calcium']), 'multi-field INN still matches');
assert.ok(queryMatches('atorvastatin calcium', ['atorva']), 'longer partial INN still matches');
const {companyExactMatch} = require('./_data_logic');
assert.ok(companyExactMatch('Công ty cổ phần dược mỹ phẩm Bảo An', baoAn));
assert.ok(companyExactMatch('CÔNG TY CỔ PHẦN DƯỢC MỸ PHẨM BẢO AN', 'Công ty cổ phần dược mỹ phẩm Bảo An'));
assert.ok(!companyExactMatch('Công ty cổ phần Dược Mỹ phẩm Quốc tế Bảo An', baoAn), 'Quốc tế Bảo An is a different firm');
assert.ok(!companyExactMatch('Công ty cổ phần dược phẩm Me Di Sun', baoAn), 'Me Di Sun must not match Bảo An');
console.log('PASS: merge identity, completeness, variants, provenance, strength units, company query tokens');
