const {chromium}=require(process.env.SRA_PLAYWRIGHT_PATH || 'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true, ...(process.env.SRA_BROWSER_CHANNEL ? {channel:process.env.SRA_BROWSER_CHANNEL} : {})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto('file:///'+path.resolve('index.html').replaceAll('\\','/'));
 await page.locator('#mq').waitFor();
 await page.waitForFunction(()=>!document.querySelector('.search-filters').inert && !document.querySelector('#vn-only').disabled);
 await page.locator('#mq').fill('atorvastatin');
 await page.locator('#mgo').click();
 await page.waitForFunction(()=>!document.querySelector('#tra-hit').textContent.includes('Đang'));
 const first=await page.locator('#tra-hit').innerText();
 assert.match(first,/dòng/);
 await page.locator('#mq').fill('atorvastatine');
 await page.locator('#mq').press('Enter');
 await page.waitForFunction(()=>document.querySelectorAll('.search-term').length===2 && !document.querySelector('#tra-hit').textContent.includes('Đang'));
 assert.equal(await page.locator('.search-term').count(),2);
 const aliases=await page.locator('#tra-hit').innerText();
 assert.ok(parseInt(aliases.replaceAll('.',''))>=parseInt(first.replaceAll('.','')));
 await page.locator('#mq').fill('ATORVASTATIN'); await page.locator('#mgo').click();
 assert.equal(await page.locator('.search-term').count(),2);
 await page.locator('[data-remove-term="1"]').click();
 await page.waitForFunction(()=>!document.querySelector('#tra-hit').textContent.includes('Đang'));
 assert.equal(await page.locator('#tra-hit').innerText(),first);
 await page.locator('[data-remove-term="0"]').click();
 await page.locator('#mq').fill('boiron');
 await page.waitForFunction(()=>!document.querySelector('#suggest').hidden);
 assert.match(await page.locator('#suggest').innerText(),/Tên thuốc|Công ty/);
 const suggestionKinds=await page.locator('#suggest .n').allTextContents();
 const priorities=suggestionKinds.map(s=>s.startsWith('Hoạt chất')?0:s.startsWith('Tên thuốc')?1:2);
 assert.deepEqual(priorities,[...priorities].sort());
 await page.locator('#mgo').click();
 await page.waitForFunction(()=>!document.querySelector('#tra-hit').textContent.includes('Đang'));
 const details=page.locator('#med-groups details').first();
 await details.locator('summary').click();
 await details.locator('tbody tr').first().waitFor();
 assert.match(await details.locator('td.co').first().innerText(),/boiron/i);
 assert.equal(await details.locator('td.co a').first().getAttribute('title'),'Website công ty');
 const product=await details.locator('td.nm').first().innerText();
 assert.equal(await details.locator('a[data-copy-product]').first().getAttribute('data-copy-product'),product);
 await page.evaluate(()=>{ Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>{window.copiedProduct=text}},configurable:true}); });
 const popupPromise=page.waitForEvent('popup');
 await details.locator('a[data-copy-product]').first().click();
 const popup=await popupPromise; await popup.close();
 assert.equal(await page.evaluate(()=>window.copiedProduct),product);
 const companyHref=await details.locator('td.co a').first().getAttribute('href');
 await details.locator('tbody input[type=checkbox]').first().check();
 const exportPromise=page.waitForEvent('download');
 await page.locator('#sel-export').click();
 const exported=await exportPromise;
 assert.ok(require('fs').readFileSync(await exported.path(),'utf8').includes(companyHref));
 for(const width of [360,390,768,1440]) {
  await page.setViewportSize({width,height:900});
  await page.locator('#tra').scrollIntoViewIfNeeded();
  await page.screenshot({path:`qa-${width}.png`});
  const overflow=await page.evaluate(()=>({doc:document.documentElement.scrollWidth,screen:innerWidth,tra:document.querySelector('#tra').getBoundingClientRect().width}));
  assert.ok(overflow.doc<=width+1,JSON.stringify(overflow));
  if(width===390){
   await details.scrollIntoViewIfNeeded();
   await page.screenshot({path:'qa-mobile-results.png'});
  }
 }
 await page.locator('#mq').fill('atorvastatin'); await page.locator('#mgo').click();
 await page.locator('#mq').fill('atorvastatine'); await page.locator('#mgo').click();
 assert.equal(await page.locator('.search-term').count(),3);
 const downloadPromise=page.waitForEvent('download');
 await page.locator('#filter-save').click();
 const download=await downloadPromise;
 const savedPath=await download.path();
 const saved=JSON.parse(require('fs').readFileSync(savedPath,'utf8'));
 assert.deepEqual(saved.terms,[{term:'boiron',kind:'Công ty'},'atorvastatin','atorvastatine']);
 await page.locator('[data-remove-term="2"]').click();
 await page.locator('#filter-file').setInputFiles(savedPath);
 await page.waitForFunction(()=>document.querySelectorAll('.search-term').length===3);
 await page.setViewportSize({width:360,height:900});
 await page.locator('#mq').scrollIntoViewIfNeeded();
 await page.screenshot({path:'qa-mobile-chips.png'});
 await page.setViewportSize({width:1600,height:1100});
 await page.locator('#health').evaluate(el=>{el.open=true});
 await page.locator('#hcov button[data-cc="FR"]').click();
 await page.locator('.health-pies').scrollIntoViewIfNeeded();
 const tops=await page.locator('#hdonut, #hqdonut, #hcdonut').evaluateAll(els=>els.map(el=>el.getBoundingClientRect().top));
 assert.ok(Math.max(...tops)-Math.min(...tops)<2,JSON.stringify(tops));
 const countryRows=await page.locator('#hcov button').evaluateAll(els=>new Set(els.map(el=>Math.round(el.getBoundingClientRect().top))).size);
 assert.equal(countryRows,3);
 await page.locator('#source-toast').evaluate(el=>el.hidden=true);
 await page.screenshot({path:'qa-health-aligned.png'});
 for(const width of [360,390,1100,1440,1600]) {
  await page.setViewportSize({width,height:1000});
  const clipped=await page.locator('#hcov button').evaluateAll(els=>els.filter(el=>el.scrollWidth>el.clientWidth+1).map(el=>el.innerText));
  assert.deepEqual(clipped,[],`Country name clipped at ${width}`);
 }
 assert.deepEqual(errors,[]);
 console.log('PASS: company search, OR aliases, duplicate prevention, chip removal, company links, mobile/tablet/desktop overflow, no JS errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
