const assert = require('node:assert/strict');
const {mergeRows, strengthMatches} = require('./_data_logic');
const row = (cc, overrides = {}) => Object.assign([cc,'substance','Product','tablet','10 mg','Company',cc === 'EMA' ? 'e' : 'd'], overrides);
let result = mergeRows([row('EMA'),row('FR')]);
assert.equal(result.length, 1);
assert.equal(result[0][0], 'FR', 'Equal completeness prefers national dump');
assert.deepEqual(new Set(result[0]._sources), new Set(['d','e']));
result = mergeRows([row('FR',{3:'',4:''}), row('EMA')]);
assert.equal(result.length,1);
assert.equal(result[0][0],'EMA','More complete EMA must win');
result = mergeRows([row('EMA',{3:'',4:''}),row('FR')]);
assert.equal(result[0][0],'FR','More complete dump must win');
assert.equal(mergeRows([row('EMA'),row('FR',{2:'Another brand'})]).length,2,'Preserve different brands');
assert.equal(mergeRows([row('EMA'),row('FR',{4:'20 mg'})]).length,2,'Preserve different strengths');
assert.equal(mergeRows([row('EMA'),row('FR',{3:'capsule'})]).length,2,'Preserve different forms');
assert.equal(mergeRows([row('EMA'),row('FR',{5:'Another MAH'})]).length,2,'Preserve conflicting holders');
assert.equal(mergeRows([row('EMA'),row('FR',{4:'0.01 g'})]).length,1,'Equivalent units');
result = mergeRows([row('EMA',{3:'',4:''}),row('EMA'),row('EMA',{4:'20 mg'}),row('FR',{2:'Local only'})]);
assert.equal(result.length,3,'Keep all presentations and local-only products');
assert.ok(strengthMatches('0.5 mg','500 mcg'));
assert.ok(strengthMatches('10 MG','10'));
assert.ok(strengthMatches('0,5 mg','0.5 mg'));
assert.ok(!strengthMatches('10 mg/ml','10 mg'),'Never confuse concentration and mass');
assert.ok(!strengthMatches('10 mg / 20 mg','10 mg'),'Never treat a combination as a single dose');
console.log('PASS: merge identity, completeness, variants, provenance, strength units');
